"""Add Company table and update Document model

Revision ID: ceb0664502e5
Revises: 716352f59159
Create Date: 2025-09-11 13:57:06.683376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb0664502e5'
down_revision: Union[str, Sequence[str], None] = '716352f59159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies', postgresql_ops={'company_name': None}, postgresql_using='prefix')
    op.drop_table('companies')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents', postgresql_ops={'content_hash': None}, postgresql_using='prefix')
    op.drop_table('documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('court', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('decision_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('document_id', name=op.f('documents_pkey')),
    sa.UniqueConstraint('content_hash', name=op.f('ix_documents_content_hash'), postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', [sa.literal_column('content_hash NULLS FIRST')], unique=True, postgresql_ops={'content_hash': None}, postgresql_using='prefix')
    op.create_table('companies',
    sa.Column('cin', sa.VARCHAR(length=21), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date_of_registration', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('company_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('registered_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cin', name=op.f('companies_pkey'))
    )
    op.create_index(op.f('ix_companies_company_name'), 'companies', [sa.literal_column('company_name NULLS FIRST')], unique=False, postgresql_ops={'company_name': None}, postgresql_using='prefix')
    # ### end Alembic commands ###
